---
title: "Calendar"
---


The calendar below lists the tentative course topics. The dates listed are subject to change at the instructor's discretion.

<!-- As part of the course, there are several articles, papers and technical reports that you will need to read during the semester. Most of the articles themselves are accessible through the [University of Minnesota library website](http://www.lib.umn.edu). In order to access the full text of some of the articles, you will need to log in using your University x500 username and password. More detailed information, including references or links to specific readings, are linked under the day's "Reading". -->

<br /><br />


<br />


<table class="table">

<thead>
<tr>
<th style="width:5%;text-align:center"></th>
<th style="width:10%;text-align:center"">Day</th>
<th style="width:10%;">Date</th>
<th style="width:15%;text-align:center">Reading</th>
<th style="width:50%;">Topic/Slides</th>
<th style="width:10%;text-align:center">Materials</th>
</tr>
</thead>


<tbody>

<!-- <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[Notes and Script file updated 09-24-2019]*</span></td> -->

<!-- READING <a class="my-link" href="readings/00-welcome-to-8264.html"><span class="fa fa-book"></span></a> -->

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">1</td>
<td style="vertical-align:middle;">Sept. 03</td>
<td align="center" style="vertical-align:middle;"></td>
<td>Welcome to EPsy 5261</td>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
</tr>


<!-- Unit 01: STATISTICAL COMPUTATION -->

<tr>
<td colspan="5"><b>Unit 01: Statistical Computation</b></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">2</td>
<td style="vertical-align:middle;">Sept. 05</td>
<td align="center" style="vertical-align:middle;"></td>
<td>
  [Introduction to Coding](https://zief0002.github.io/slides/d02-introduction-to-coding.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines"></span>](https://docs.google.com/document/d/1UtUi8VrrP_o2vIiWJ-7EehTynZ7SmQjl8MhIvCLjbt8/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">3</td>
<td style="vertical-align:middle;">Sept. 10</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 1--2](https://zief0002.github.io/epsy-5261/01-01-r-and-rstudio-installation.html)
</td>
<td>
  [Introduction to R and RStudio](https://zief0002.github.io/slides/d03-introduction-to-r-and-rstudio.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines"></span>](https://docs.google.com/document/d/1MkciLSJRREZ60Pm2TMkeGDZLFR4E7tcwz9J8uE2xP0w/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">4</td>
<td style="vertical-align:middle;">Sept. 12</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 4](https://zief0002.github.io/epsy-5261/02-00-data.html)
</td>
<td>
  Data and Codebooks
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines"></span>](https://docs.google.com/document/d/1GLKCpirEcdupTeyWCt4XOS-82tCS7ybgiB_ZE_0s3NQ/edit?usp=sharing)
</td>
</tr>

<!-- Unit 02: SUMMARIZING AND VISUALIZING DATA -->

<tr>
<td colspan="5"><b>Unit 02: Visualizing and Summarizing Data</b></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">5</td>
<td style="vertical-align:middle;">Sept. 17</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 5--6](https://zief0002.github.io/epsy-5261/03-00-exploring-and-describing-data.html)
</td>
<td>
  [Variables and Graphs](https://zief0002.github.io/slides/d05-variables-and-graphs.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines"></span>](https://docs.google.com/document/d/1Dlw340KE1dW1PcEhYy-UQ8jNbFxS1S9gTceVIS7m5xk/edit?usp=sharing)
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">6</td>
<td style="vertical-align:middle;">Sept. 19</td>
<td align="center" style="vertical-align:middle;"></td>
<td>
  [Describing Distributions](https://zief0002.github.io/slides/d06-describing-distributions.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1V4K0wb3F-tUAflKlCk8oxsiCzPcPurIZDSQ4Ztxn1eA/edit?usp=sharing)
</td>
</tr>


<!-- Unit 03: COMPARING DATA TO A STANDARD -->

<tr>
<td colspan="5"><b>Unit 03: Comparing Data to a Standard</b></td>
</tr>



<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">7</td>
<td style="vertical-align:middle;">Sept. 24</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 7--8](https://zief0002.github.io/epsy-5261/04-00-comparing-to-a-standard.html)
</td>
<td>
  [Estimating Uncertainty](https://zief0002.github.io/slides/d07-estimating-uncertainty.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1mj6nNc3TgHCDLsVz34r3WPt4wToDmAH1c4HlhSH3ktM/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">8</td>
<td style="vertical-align:middle;">Sept. 26</td>
<td align="center" style="vertical-align:middle;"></td>
<td>
  [Introduction to Hypothesis Testing](https://zief0002.github.io/slides/d08-introduction-to-hypothesis-testing.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1l5_sCH4tEetLjgQp794IM7CMiq_4iWHMGSU7EgL35dc/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">9</td>
<td style="vertical-align:middle;">Oct. 01</td>
<td align="center" style="vertical-align:middle;"></td>
<td>
  [Hypothesis Testing with Simulation](https://zief0002.github.io/slides/d09-simulation-based-hypothesis-testing.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1BtqnaKPX4z3Vi1WneBhQ3szZ3IN8TzhFY-l8f4y0Hzc/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">10</td>
<td style="vertical-align:middle;">Oct. 03</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 17](https://zief0002.github.io/epsy-5261/06-01-generalization.html)
</td>
<td>
  [Study Design: Generalizations](https://zief0002.github.io/slides/d10-study-design-generalizability.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1Yg2ngMHEc1t0GXpm9PXsCYxaiQ7Rx9zvuZ6CxOCT2Yc/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">11</td>
<td style="vertical-align:middle;">Oct. 08</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 9--11](https://zief0002.github.io/epsy-5261/04-03-one-sample-test.html)
</td>
<td>
  [Introduction to Hypothesis Testing with the *t*-Distribution](https://zief0002.github.io/slides/d11-hypothesis-testing-with-the-t-distribution.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1XKDInpEEclP2Xg6_R5WtKqOKRDHjTh0nK60Rx7r5b8E/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">12</td>
<td style="vertical-align:middle;">Oct. 10</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 12](https://zief0002.github.io/epsy-5261/04-06-one-sample-test-proportions.html)
</td>
<td>
  [Introduction to Hypothesis Testing with the *z*-Distribution](https://zief0002.github.io/slides/d12-hypothesis-testing-for-proportions.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1hmxrvxC44zGcAmsEeED5lV8LobQ0pNZKzt-6UvrY-NU/edit?usp=sharing)
</td>
</tr>


<!-- Unit 04: COMPARING TWO GROUPS -->

<tr>
<td colspan="5"><b>Unit 04: Comparing Two Groups</b></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">13</td>
<td style="vertical-align:middle;">Oct. 15</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 18](https://zief0002.github.io/epsy-5261/06-02-cause-and-effect.html)
</td>
<td>
  [Study Design: Causal Claims](https://zief0002.github.io/slides/d13-study-design-causal-claims.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1tMVSpad7xrDu2C3EL5FSDAjzlMeW61ZheP2nsLbxU_0/edit?usp=sharing)
</td>
</tr>



<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">14</td>
<td style="vertical-align:middle;">Oct. 17</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 13--14](https://zief0002.github.io/epsy-5261/05-01-two-sample-t-test.html)
</td>
<td>
  [Introduction to Hypothesis Testing: Comparing Two Means](https://zief0002.github.io/slides/d14-hypothesis-testing-for-comparing-two-means.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1n0jhSWsDaw2jekeEMcSBsbtShLbrrkspxrEVReKjJaY/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">15</td>
<td style="vertical-align:middle;">Oct. 22</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 15](https://zief0002.github.io/epsy-5261/05-03-two-sample-test-proportions.html)
</td>
<td>
  [Introduction to Hypothesis Testing: Comparing Two Proportions](https://zief0002.github.io/slides/d15-hypothesis-testing-for-comparing-two-proportions.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/16UOmsD1x_f3PuoISDACcTBHFlA0VNABlKCpG8OS0DEM/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">16</td>
<td style="vertical-align:middle;">Oct. 24</td>
<td align="center" style="vertical-align:middle;"></td>
<td style="vertical-align:middle;">NO CLASS---Mental Health Day 🛌 🍷</td>
<td align="center" style="vertical-align:middle;"></td>
</tr>


<!-- Unit 05: EFFECT SIZE -->

<tr>
<td colspan="5"><b>Unit 05: Effect Size</b></td>
</tr>


<tr>
<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">17</td>
<td style="vertical-align:middle;">Oct. 29</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 19--21](https://zief0002.github.io/epsy-5261/07-00-effect-size.html)
</td>
<td>
  [Introduction to Confidence Intervals](https://zief0002.github.io/slides/d17-introduction-to-confidence-intervals.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/14TAjxPQ207cD2eIs-mUnCDU8p-e1FBhUY0w7xPJmFFM/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">18</td>
<td style="vertical-align:middle;">Oct. 31</td>
<td align="center" style="vertical-align:middle;"></td>
<td>
  [Confidence Intervals for a Single Mean](https://zief0002.github.io/slides/d18-confidence-interval-for-a-single-mean.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1Vuko7V6zTlSa2L_j3-Wd4KjU8RD_OqiO7E9nVFXvoUY/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">19</td>
<td style="vertical-align:middle;">Nov. 05</td>
<td align="center" style="vertical-align:middle;"></td>
<td>
  <!-- Confidence Intervals for a Single Proportion -->
  [Confidence Intervals for a Single Proportion](https://zief0002.github.io/slides/d19-confidence-interval-for-a-single-proportion.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/13XY4LgiScfgXRSdiKKCmrRcfjZmvaMN-nDcQ3ZD2GZ0/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">20</td>
<td style="vertical-align:middle;">Nov. 07</td>
<td align="center" style="vertical-align:middle;"></td>
<td>
  [Confidence Intervals for Comparing Two Groups](https://zief0002.github.io/slides/d20-confidence-interval-for-comparing-two-groups.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1BQUpHZiUmxUmR_h-vJsQef_NaqL9rg6pP_h5G-SLkA0/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">21</td>
<td style="vertical-align:middle;">Nov. 12</td>
<td align="center" style="vertical-align:middle;"></td>
<td>
<!-- Confidence Intervals for Comparing Two Proportions -->
  [Practice with Confidence Intervals](https://zief0002.github.io/slides/d21-practice-confidence-intervals.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1e1O94_ffK8XDwfNLUO7Zjf5y1TyZsgfEZPhoDNC9H88/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">22</td>
<td style="vertical-align:middle;">Nov. 14</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 22--23](https://zief0002.github.io/epsy-5261/07-04-standardized-effects-means.html)
</td>
<td>
  [Exploring Effect Size](https://zief0002.github.io/slides/d22-exploring-effect-size.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/14y_iMAm1L39MI8sqV6GrSF0iyfUmGvt3RiJcyNNonew/edit?usp=sharing)
</td>
</tr>


<!-- Unit 06: CORRELATION AND REGRESSION -->

<tr>
<td colspan="5"><b>Unit 06: Correlation and Regression</b></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">23</td>
<td style="vertical-align:middle;">Nov. 19</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 24](https://zief0002.github.io/epsy-5261/08-01-scatterplot-correlation.html)
</td>
<td>
  [Introduction to Correlation](https://zief0002.github.io/slides/d23-introduction-to-correlation.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1pexBnC74XcTUuQvahea9ZGe9sxJPKiFDCmLNaogOkXU/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">24</td>
<td style="vertical-align:middle;">Nov. 21</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 25--26](https://zief0002.github.io/epsy-5261/08-02-linear-regression-description.html)
</td>
<td>
  [Introduction to Linear Regression](https://zief0002.github.io/slides/d24-introduction-to-linear-regression.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1Rq0zPyVaqgda8iQzfOM4v3nGlYgqYYSI2I-1DSnhUiw/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">25</td>
<td style="vertical-align:middle;">Nov. 26</td>
<td align="center" style="vertical-align:middle;">
  [Ch. 27](https://zief0002.github.io/epsy-5261/08-04-regression-inference.html)
</td>
<td>
  [Hypothesis Test for the Slope](https://zief0002.github.io/slides/d25-hypothesis-test-for-a-slope.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/12LFw_scE-dp58GBjBXQI43AEm3o6E2kUlHjFbY1uu8s/edit?usp=sharing)
</td>
</tr>


<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;">&nbsp;</td> -->
<!-- <td align="center" style="vertical-align:middle;">23</td> -->
<!-- <td style="vertical-align:middle;">Nov. 21</td> -->
<!-- <td align="center" style="vertical-align:middle;"></td> -->
<!-- <td style="vertical-align:middle;">NO CLASS---Mental Health Day 🛌 🍷</td> -->
<!-- <td align="center" style="vertical-align:middle;"></td> -->
<!-- </tr> -->


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">26</td>
<td style="vertical-align:middle;">Nov. 28</td>
<td align="center" style="vertical-align:middle;"></td>
<td style="vertical-align:middle;">NO CLASS---Thanksgiving Break 🦃 🌽 🥧</td>
<td align="center" style="vertical-align:middle;"></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">27</td>
<td style="vertical-align:middle;">Dec. 03</td>
<td align="center" style="vertical-align:middle;"></td>
<td>
  [Assumptions for Linear Regression](https://zief0002.github.io/slides/d27-assumptions-for-linear-regression.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1GJb_hy4Mht87S2sIYpS4OO1ZLY-3iDc83utN6ODFLkw/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">28</td>
<td style="vertical-align:middle;">Dec. 05</td>
<td align="center" style="vertical-align:middle;"></td>
<td>
  Linear Regression: Practice
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1jtP87DCGf4qnbzDOIySjCa-4N0X7ssJp6ydIu4PI9w8/edit?usp=sharing)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td align="center" style="vertical-align:middle;">29</td>
<td style="vertical-align:middle;">Dec. 10</td>
<td align="center" style="vertical-align:middle;"></td>
<td>
  TBD
  <!-- [Review Day](https://zief0002.github.io/slides/d29-review.html) -->
</td>
<td align="center" style="vertical-align:middle;">
  <!-- [<span class="fa-solid fa-file-lines">](https://docs.google.com/document/d/1hmxrvxC44zGcAmsEeED5lV8LobQ0pNZKzt-6UvrY-NU/edit?usp=sharing) -->
</td>
</tr>





</tbody>
</table>    


